# Generated by Django 5.0.14 on 2025-05-07 09:05

import taggit.managers
import utilities.json
from django.db import migrations, models

import netbox_ninja_plugin.ninja_template.logic


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0010_gfk_indexes"),
        ("extras", "0116_custom_link_button_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="NinjaTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("output_type", models.CharField(default="", max_length=32)),
                ("code", models.TextField(blank=True)),
                (
                    "object_types",
                    models.ManyToManyField(
                        blank=True, related_name="ninja_templates", to="core.objecttype"
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(
                netbox_ninja_plugin.ninja_template.logic.NinjaTemplateMixin,
                models.Model,
            ),
        ),
    ]
