# Generated by Django 5.1.8 on 2026-03-26 12:25

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_concrete_objecttype"),
        ("extras", "0132_configcontextprofile"),
        ("netbox_ninja_plugin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ninjatemplate",
            name="object_type_filters",
            field=models.ManyToManyField(
                blank=True, related_name="object_type_filters", to="core.objecttype"
            ),
        ),
        migrations.CreateModel(
            name="NinjaTemplateStringFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "key",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Key must contain only alphanumeric characters (A-Z, a-z, 0-9).",
                                regex="^[A-Za-z0-9]+$",
                            )
                        ],
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "ninja template string filter",
                "verbose_name_plural": "ninja template string filters",
                "ordering": ["name"],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="ninjatemplate",
            name="string_filters",
            field=models.ManyToManyField(
                blank=True,
                related_name="ninja_templates",
                to="netbox_ninja_plugin.ninjatemplatestringfilter",
            ),
        ),
        migrations.CreateModel(
            name="NinjaTemplateStringFilterOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=255)),
                (
                    "string_filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="netbox_ninja_plugin.ninjatemplatestringfilter",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "ninja template string filter option",
                "verbose_name_plural": "ninja template string filter options",
                "ordering": ["string_filter__name", "value"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("string_filter", "value"),
                        name="unique_string_filter_option_value",
                    )
                ],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
